- hosts: all
  become: yes
  roles:
  - sudoers
  - tools
  - userpython
  - buildah
  - rpmfusion
 # - password-store
  - sublime
  - git-annex
  
  
- hosts: all
  roles:
  - repositories
  #- user_annex
  - pre-commit
 
