- name: enable rpmfusion for {{ansible_distribution_version}} {{item}}
  dnf:
    name:
      https://download1.rpmfusion.org/{{item}}/fedora/rpmfusion-{{item}}-release-{{ansible_distribution_version}}.noarch.rpm 
    disable_gpg_check: yes
  loop:
  - free
  - nonfree

#- yum_repository:
  
