
- file:
    path: ~/.local/venvs
    state: directory
- name: ensure pre-commit venv
  pip:
    name: pre-commit
    state: latest
    virtualenv: ~/.local/venvs/pre-commit
- name: ensure bin dir
  file:
    state: directory
    dest: ~/.local/bin
- name: link pre-commit to main
  file:
    state: link
    src: ~/.local/venvs/pre-commit/bin/pre-commit
    dest: ~/.local/bin/pre-commit